version: '3.7'

services:
  server:
    build: .
    volumes:
      - "./app:/app"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=comment_analyzer
      - POSTGRES_PASSWORD=comment_analyzer_password
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    expose:
      - 5432

volumes:
  postgres_data: